import {test} from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import http from 'node:http';
import {createControlServer} from '../deploy/control/server.mjs';

async function fixture(t,runRelease=async()=>{},inspectRelease) {
  const directory=await fs.mkdtemp(path.join(os.tmpdir(),'tms-control-test-'));
  const options={stateDirectory:path.join(directory,'control'),secretDirectories:Object.fromEntries(['database','migrator','api','worker','storage'].map(name=>[name,path.join(directory,name)])),runRelease,inspectRelease,origin:()=>origin};
  let origin='';
  const server=await createControlServer(options);
  await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
  origin=`http://127.0.0.1:${server.address().port}`;
  t.after(async()=>{server.closeAllConnections();await new Promise(resolve=>server.close(resolve));await fs.rm(directory,{recursive:true,force:true});});
  let cookie='';
  const request=async(route,body,overrides={})=>{
    const response=await fetch(origin+route,{method:body?'POST':'GET',headers:{...(cookie?{Cookie:cookie}:{}),...(body?{Origin:origin,'Content-Type':'application/json'}:{}),...overrides},body:body?JSON.stringify(body):undefined});
    if(response.headers.get('set-cookie'))cookie=response.headers.get('set-cookie').split(';')[0];
    return {status:response.status,body:await response.json(),headers:response.headers};
  };
  const unlock=async()=>request('/api/control/unlock',{code:await fs.readFile(path.join(options.stateDirectory,'operator-code'),'utf8')});
  return {directory,options,server,request,unlock,get cookie(){return cookie;}};
}

test('unpaired requests cannot read installer state',async t=>{const f=await fixture(t);const r=await f.request('/api/control');assert.equal(r.status,401);assert.equal(r.body.code,'unlock_required');});
test('unknown operator code cannot pair',async t=>{const f=await fixture(t);assert.equal((await f.request('/api/control/unlock',{code:'wrong'})).status,401);});
test('malformed and multibyte operator codes fail authentication without a server exception',async t=>{const f=await fixture(t);for(const code of [12,{},'é'.repeat(64)])assert.equal((await f.request('/api/control/unlock',{code})).status,401);});
test('paired access has a server-enforced expiry after restart',async t=>{const f=await fixture(t);await f.unlock();const file=path.join(f.options.stateDirectory,'operator-session-hash');const session=JSON.parse(await fs.readFile(file,'utf8'));assert.ok(Number.isFinite(session.expiresAt));session.expiresAt=0;await fs.writeFile(file,JSON.stringify(session));const second=await createControlServer({...f.options,origin:()=>secondOrigin});await new Promise(resolve=>second.listen(0,'127.0.0.1',resolve));const secondOrigin=`http://127.0.0.1:${second.address().port}`;t.after(()=>second.close());const r=await fetch(secondOrigin+'/api/control',{headers:{Cookie:f.cookie}});assert.equal(r.status,401);});
test('pairing sets a strict HttpOnly session and consumes one-use code',async t=>{const f=await fixture(t);const code=await fs.readFile(path.join(f.options.stateDirectory,'operator-code'),'utf8');const r=await f.unlock();assert.equal(r.status,200);assert.match(r.headers.get('set-cookie'),/HttpOnly/);assert.match(r.headers.get('set-cookie'),/SameSite=Strict/);assert.equal(r.body.state,'needs_configuration');assert.equal((await f.request('/api/control/unlock',{code})).status,401);});
test('Host and cross-origin mutations are rejected',async t=>{const f=await fixture(t);const origin=f.options.origin();const status=await new Promise((resolve,reject)=>{http.get(origin+'/api/control',{headers:{Host:'attacker.example'}},response=>{response.resume();resolve(response.statusCode);}).on('error',reject);});assert.equal(status,403);assert.equal((await f.request('/api/control/unlock',{code:'x'},{Origin:'https://attacker.example'})).status,403);});
test('paired mutations require the current CSRF token',async t=>{const f=await fixture(t);await f.unlock();assert.equal((await f.request('/api/control/configure',{appPort:8180,csrfToken:'wrong'})).status,403);});
test('settings validate integer nonprivileged ports and reject unknown fields',async t=>{const f=await fixture(t);const s=(await f.unlock()).body;for(const appPort of [80,65536,8180.5,'8180',null])assert.equal((await f.request('/api/control/configure',{appPort,csrfToken:s.csrfToken})).status,422);assert.equal((await f.request('/api/control/configure',{appPort:8180,csrfToken:s.csrfToken,image:'evil'})).status,422);});
test('configure durably stores typed settings and distinct secret files without disclosing secrets',async t=>{const f=await fixture(t);const s=(await f.unlock()).body;const r=await f.request('/api/control/configure',{appPort:8180,csrfToken:s.csrfToken});assert.equal(r.status,200);assert.equal(r.body.state,'configured');assert.equal(r.body.appPort,8180);const secretNames={database:'db_password',migrator:'migrator_password',api:'api_password',worker:'worker_password'};const secrets=await Promise.all(Object.entries(secretNames).map(([name,file])=>fs.readFile(path.join(f.options.secretDirectories[name],file),'utf8')));assert.equal(new Set(secrets).size,4);for(const secret of secrets){assert.match(secret,/^[a-f0-9]{64}$/);assert.ok(!JSON.stringify(r.body).includes(secret));}assert.equal(JSON.parse(await fs.readFile(path.join(f.options.stateDirectory,'state.json'),'utf8')).appPort,8180);});
test('deployment requires configuration and never accepts commands or releases',async t=>{const f=await fixture(t);const s=(await f.unlock()).body;assert.equal((await f.request('/api/control/deploy',{csrfToken:s.csrfToken})).status,409);await f.request('/api/control/configure',{appPort:8180,csrfToken:s.csrfToken});assert.equal((await f.request('/api/control/deploy',{csrfToken:s.csrfToken,command:'rm -rf /'})).status,422);assert.equal((await f.request('/api/control/deploy',{csrfToken:s.csrfToken,release:'other'})).status,422);});
test('concurrent deployments serialize and success reflects the runner outcome',async t=>{let release;let calls=0;const wait=new Promise(resolve=>release=resolve);const f=await fixture(t,async()=>{calls++;await wait;});const s=(await f.unlock()).body;await f.request('/api/control/configure',{appPort:8180,csrfToken:s.csrfToken});const r=await f.request('/api/control/deploy',{csrfToken:s.csrfToken});assert.equal(r.status,202);assert.equal(r.body.state,'deploying');assert.equal((await f.request('/api/control/deploy',{csrfToken:s.csrfToken})).status,409);assert.equal((await f.request('/api/control/configure',{appPort:8280,csrfToken:s.csrfToken})).status,409);release();await new Promise(resolve=>setTimeout(resolve,50));const done=await f.request('/api/control');assert.equal(calls,1);assert.equal(done.body.state,'ready');assert.equal(done.body.job.state,'succeeded');});
test('deployment failure is actionable without exposing engine output or secrets',async t=>{const f=await fixture(t,async()=>{throw Error('secret=do-not-disclose engine diagnostic');});const s=(await f.unlock()).body;await f.request('/api/control/configure',{appPort:8180,csrfToken:s.csrfToken});await f.request('/api/control/deploy',{csrfToken:s.csrfToken});await new Promise(resolve=>setTimeout(resolve,50));const r=await f.request('/api/control');assert.equal(r.body.state,'failed');assert.equal(r.body.job.state,'failed');assert.ok(!JSON.stringify(r.body).includes('do-not-disclose'));assert.match(r.body.job.message,/retry|Retry/);});
test('actual service degradation and recovery update current control readiness',async t=>{let healthy=true;const inspect=async()=>['database','storage','migrate','api','worker','web'].map(name=>({name,state:name==='migrate'?'completed':!healthy&&name==='storage'?'failed':'healthy'}));const f=await fixture(t,async()=>{},inspect);const s=(await f.unlock()).body;await f.request('/api/control/configure',{appPort:8180,csrfToken:s.csrfToken});await f.request('/api/control/deploy',{csrfToken:s.csrfToken});await new Promise(resolve=>setTimeout(resolve,50));assert.equal((await f.request('/api/control')).body.state,'ready');healthy=false;assert.equal((await f.request('/api/control')).body.state,'failed');healthy=true;const restored=await f.request('/api/control');assert.equal(restored.body.state,'ready');assert.equal(restored.body.job.state,'succeeded');});
test('control state survives restart independently of application database',async t=>{const f=await fixture(t);const s=(await f.unlock()).body;await f.request('/api/control/configure',{appPort:8180,csrfToken:s.csrfToken});const second=await createControlServer({...f.options,origin:()=>secondOrigin});await new Promise(resolve=>second.listen(0,'127.0.0.1',resolve));const secondOrigin=`http://127.0.0.1:${second.address().port}`;t.after(()=>second.close());const r=await fetch(secondOrigin+'/api/control',{headers:{Cookie:f.cookie}});assert.equal(r.status,200);assert.equal((await r.json()).appPort,8180);});
test('interrupted deployment is durably failed and can be retried instead of reporting ready',async t=>{const f=await fixture(t);const s=(await f.unlock()).body;await f.request('/api/control/configure',{appPort:8180,csrfToken:s.csrfToken});const stateFile=path.join(f.options.stateDirectory,'state.json');const state=JSON.parse(await fs.readFile(stateFile,'utf8'));state.state='deploying';state.job={id:'interrupted',state:'running',message:'Deploying'};await fs.writeFile(stateFile,JSON.stringify(state));const second=await createControlServer({...f.options,origin:()=>secondOrigin});await new Promise(resolve=>second.listen(0,'127.0.0.1',resolve));const secondOrigin=`http://127.0.0.1:${second.address().port}`;t.after(()=>second.close());const r=await fetch(secondOrigin+'/api/control',{headers:{Cookie:f.cookie}});const body=await r.json();assert.equal(body.state,'failed');assert.equal(body.job.state,'failed');});
